/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeepsakesRouteImport } from './routes/keepsakes'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepsakesRoute = KeepsakesRouteImport.update({
  id: '/keepsakes',
  path: '/keepsakes',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keepsakes': typeof KeepsakesRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keepsakes': typeof KeepsakesRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keepsakes': typeof KeepsakesRoute
  '/game/$gameId': typeof GameGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/keepsakes' | '/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/keepsakes' | '/game/$gameId'
  id: '__root__' | '/' | '/keepsakes' | '/game/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeepsakesRoute: typeof KeepsakesRoute
  GameGameIdRoute: typeof GameGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keepsakes': {
      id: '/keepsakes'
      path: '/keepsakes'
      fullPath: '/keepsakes'
      preLoaderRoute: typeof KeepsakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeepsakesRoute: KeepsakesRoute,
  GameGameIdRoute: GameGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
